mqtt:
  enabled: false

cameras:
  Dog:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Dog # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio # <- only necessary if audio detection is enabled

go2rtc:
  streams:
    Dog:
      - rtspx://192.168.1.1:7441/o8l2ieYwockQhVGh