substitutions:
  name: apollo-msr-2-3574ec
  friendly_name: Apollo MSR-2
packages:
  ApolloAutomation.MSR-2: github://ApolloAutomation/MSR-2/Integrations/ESPHome/MSR-2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: QF7baaI04Nfzk8+rrIj3tk3M8fOuCqd4sYgq+TPfX50=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
