esphome:
  name: colour-and-light-sensor
  friendly_name: APDS9960 Colour Sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "giu8C5ZwFTkCi+3izw9TX/QzXube+P50E2Eziflu200="

ota:
  password: "34af0941f536aa2d0dfb025676510f14"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

button:
  - platform: restart
    name: "Restart"

i2c:
  sda: 32
  scl: 33
  scan: true

# Example configuration entry
apds9960:
  address: 0x39
  update_interval: 5s
  ambient_light_gain: 64x

sensor:
  # - platform: apds9960
  #   type: CLEAR
  #   name: "Clear"

  # - platform: apds9960
  #   type: PROXIMITY
  #   name: "Proximity"

  - platform: apds9960
    type: RED
    id: apds9960_red
    name: "Red"

  - platform: apds9960
    type: GREEN
    name: "Green"

  - platform: apds9960
    type: BLUE
    name: "Blue"

binary_sensor:
  - platform: template
    name: "Fetch TV Power"
    lambda: |-
      if (id(apds9960_red).state > 1.9) {
        // Fetch TV is OFF
        return false;
      } else {
        // Fetch TV is ON
        return true;
      }
#   - platform: apds9960
#     direction: UP
#     name: "Up Movement"

#   - platform: apds9960
#     direction: DOWN
#     name: "Down Movement"

#   - platform: apds9960
#     direction: LEFT
#     name: "Left Movement"

#   - platform: apds9960
#     direction: RIGHT
#     name: "Right Movement"
