esphome:
  name: k-type-thermocouple
  friendly_name: K-Type Thermocouple

esp32:
  board: tinypico
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "5qdtf6PfOcXoPn8pyho9SJz2/2QVXsNs3W20bLBBY98="

ota:
  password: "73f76709b24dde7788fcb94aa1c54ee0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  sda: 21
  scl: 22
  scan: true
  frequency: 10kHz # Only works at 10KHz despite ESPHome documentation saying must be >= 100kHz

sensor:
  - platform: mcp9600
    hot_junction:
      name: "Thermocouple Temperature"
    cold_junction:
      name: "Ambient Temperature"
    thermocouple_type: K
    address: 0x67
    update_interval: 10s