substitutions:
  min_brightness: "10" # Minimum LED strip brightness using push button on Stamp-Pico %
  max_brightness: "100" # Maximum LED strip brightness using push button on Stamp-Pico %
  rgb_led_brightness: "100%"

esphome:
  name: led-strip-fire-pit
  friendly_name: LED Strip Fire Pit
  comment: White LED strip dimmer on M5Stack Stamp-Pico
  on_boot:
    priority: 600
    then:
      # - light.turn_on:
      #     id: stamp_led 
      #     effect: 'Rainbow'
      #     brightness: 100%
      # - delay: 5s
      - light.turn_on:
          id: stamp_led
          effect: 'None'
          color_brightness: ${rgb_led_brightness}
          red: 0%
          green: 0%
          blue: 100%
      - delay: 600ms
      - light.turn_off:
          id: stamp_led 
      # - light.turn_on:
      #     id: led_strip
      #     brightness: 25%

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: hSJpp4CsxCC1YSW7NtHlW1H2oMZ1u0wnk5N6Mn8Iu5M=

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.20.195
    gateway: 192.168.20.1
    subnet: 255.255.255.0

button:
  - platform: restart
    name: ESP32 restart

globals:
  id: dimmer_up
  type: bool
  initial_value: 'true'

dallas:
  - pin: 25
    update_interval: 5s

sensor:
  - platform: dallas
    name: DS18B20
    id: pcb_temperature
    address: 0x993c01a816a26a28
    accuracy_decimals: 1
    filters:
      - offset: -0.5
      - sliding_window_moving_average:
          window_size: 3
          send_every: 6

binary_sensor:
  - platform: gpio
    id: push_button
    internal: True
    pin:
      number: 39
      inverted: True
    filters:
      - delayed_on: 20ms
    on_click:
      - min_length: 30ms
        max_length: 400ms
        then:
          - light.toggle: led_strip
          - delay: 500ms

    on_press:
      then:
        - while:
            condition:
              lambda: |-
                // ESP_LOGI("button debug", "button_state=%s", id(push_button).state ? "True" : "False");
                return (id(led_strip).current_values.is_on() && id(push_button).state); // LED strip is currently ON && button is still held
            then:
              - if:
                  condition:
                    lambda: 'return id(dimmer_up);'
                  then:
                    - light.dim_relative:
                        id: led_strip
                        relative_brightness: 2.5%
                    - lambda: |-
                        float curr_bright = id(led_strip).current_values.get_brightness() * 100.0;
                        ESP_LOGI("light debug", "led_strip brightness = %.1f", curr_bright);
                        if (curr_bright >= ${max_brightness}) {
                          id(dimmer_up) = false;
                          delay(1500);
                        }
                  else:
                    - light.dim_relative:
                        id: led_strip
                        relative_brightness: -2.5%
                    - lambda: |-
                        float curr_bright = id(led_strip).current_values.get_brightness() * 100.0;
                        ESP_LOGI("light debug", "led_strip brightness = %.2f", curr_bright);
                        if (curr_bright <= ${min_brightness}) {
                          id(dimmer_up) = true;
                          delay(1500);
                        }
              - delay: 150ms

light:
  - platform: neopixelbus
    id: stamp_led
    internal: True
    variant: SK6812
    pin: GPIO27
    num_leds: 1
    type: GRB
    # restore_mode: ALWAYS_OFF
    default_transition_length: 100ms
    effects:
      - addressable_rainbow:
          name: Rainbow
          width: 1

  # This is the dimmer light
  - platform: monochromatic
    output: dimmer_pin
    id: led_strip
    name: Dimmer
    default_transition_length: 100ms
    # The following code just blinks the RGB LED for 2s on each ON/OFF transition
    on_turn_on:
      - light.turn_on:
          id: stamp_led
          color_brightness: ${rgb_led_brightness}
          red: 0%
          green: 100%
          blue: 0%
      - delay: 2s
      - light.turn_off:
          id: stamp_led
    on_turn_off:
      - light.turn_on:
          id: stamp_led
          color_brightness: ${rgb_led_brightness}
          red: 100%
          green: 0%
          blue: 0%
      - delay: 2s
      - light.turn_off:
          id: stamp_led 

output:
  - platform: ledc
    pin: 32
    id: dimmer_pin
    frequency: 1220Hz
    