substitutions:
  name: olimex-bluetooth-proxy-c22bf4
  friendly_name: Bluetooth Proxy c22bf4
packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/olimex-esp32-poe-iso.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: bmt1hoeG5iN7dgbvlAFgOEujKttobyrK4JfNvRqkOLw=
