substitutions:
  dev_name: "power-monitor-workshop"
  friend_name: "Power Monitor Workshop"
  room_light: light.workshop_downlight

packages:
  device_base: !include packages/core2-power-monitor.yaml
