esphome:
  name: rack-fan-controller
  friendly_name: Rack Fan Controller

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "SZSdMUGh8U5Jdeiv/b0UUgBdSEy4MRskbPWSE6iwAbA="

ota:
  - platform: esphome
    password: "049de76efa80d7a6184acb13552e483d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: pulse_counter
    update_interval: 5s
    pin: 
      number: GPIO25
      mode: INPUT_PULLUP
    unit_of_measurement: 'RPM'
    id: fan_speed
    name: Fan Speed
    accuracy_decimals: 0
    filters:
      - multiply: 0.5  # Depending on how many pulses the fan sends per round - should be 0.5 or 1 - try...

output:
  # Wire this pin (13) into the PWM pin of your 12v fan
  # ledc is the name of the pwm output system on an esp32
  - platform: ledc
    id: fan_pwm_control
    pin: GPIO32

    # 25KHz is standard PC fan frequency, minimises buzzing
    frequency: "25000 Hz" 

    # my fans stop working below 13% powerful.
    # also they're  powerful and loud, cap their max speed to 80%
    # min_power: 13%
    # max_power: 80%

    # At 0, actually turn it off, otherwise the power keeps going.
    zero_means_zero: true

fan:
  - platform: speed
    id: manual_fan_control
    output: fan_pwm_control
    name: "Manual Fan Speed"