esphome:
  name: "seven-seg-disp"
  friendly_name: Seven Segment Display
  min_version: 2024.11.0
  name_add_mac_suffix: false
  comment: Seven Segment Display with 22xWS2812B LED string

esp32:
  board: um_tinys3
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

number:
  - platform: template
    name: LED Strip Brightness
    id: brightness_led_strip
    initial_value: 20
    optimistic: True
    min_value: 0
    max_value: 100
    step: 10
    mode: slider
  - platform: template
    name: Simulate Battery
    id: sim_batt
    initial_value: 40
    optimistic: True
    min_value: 0
    max_value: 100
    step: 1
    mode: slider

light:
  # - platform: neopixelbus
  - platform: esp32_rmt_led_strip
    id: rgb_led_strip
    name: RGB LED Strip
    internal: False
    # rmt_channel: 0
    chipset: WS2812
    pin: 1
    num_leds: 22
    rgb_order: GRB
    default_transition_length: 100ms
    effects:
      - addressable_rainbow:
          name: Rainbow
          width: 20
      - addressable_scan:
          name: Scan 3
          move_interval: 200ms

interval:
  - interval: 1s
    then:
      - light.addressable_set:
          # clear all LEDs first
          id: rgb_led_strip
          range_from: 0
          range_to: 21
          red: 0%
          green: 0%
          blue: 0%
      - light.addressable_set:
          id: rgb_led_strip
          color_brightness: !lambda 'return id(brightness_led_strip).state / 100.0;'
          range_from: 0
          range_to: !lambda |-
            // return (int)round(id(ha_tesla_battery).state / 10.0) - 1;
            float led_num = round(id(sim_batt).state / 4.5) - 1.0;
            if (led_num < 0) led_num = 0;
            ESP_LOGW("", "sim batt to LED number = %.1f", led_num);
            return (int)led_num;
          red: 0%
          green: 100%
          blue: 0%
