substitutions:
  shed_lawn_name: Shed Lawn        # zone 1 / Valve 0
  ramp_lawn_name: Ramp Lawn        # zone 2 / Valve 1
  back_lawn_name: Back Lawn        # zone 3 / Valve 2
  back_garden_name: Back Garden    # zone 4 / Valve 3
  pool_garden_name: Pool Garden    # zone 5 / Valve 4
  front_garden_name: Front Garden  # zone 6 / Valve 5
  front_lawn_name: Front Lawn      # zone 7 / Valve 6
  verge_lawn_name: Verge Lawn      # zone 8 / Valve 7
  # initial sprinkler run time in minutes. Set for spring/autumn and use multiplier/divide to adjust for summer/winter
  initial_runtime_mins: "10"
  # max runtime for number exposed to HA front end
  max_runtime_mins: "60"

globals:
  - id: current_program_str
    type: std::string
    restore_value: no  # Strings cannot be saved/restored
    initial_value: '"No program"'

esphome:
  name: sprinkler
  friendly_name: "Sprinkler"
  comment: ESP32 Sprinkler controller using LilyGo T-Relay (8x channel) board.
  includes:
    - esp_home_functions.h
  on_boot:
    - priority: 600
      then:
        - repeat:
            count: 5
            then:
              - light.turn_on: status_led
              - light.addressable_set:
                  id: rgb
                  range_from: 0
                  range_to: 0
                  color_brightness: 100%
                  red: 0.0
                  green: 1.0
                  blue: 0.0
              - delay: 200ms
              - light.turn_off: status_led
              - light.turn_off: rgb
              - delay: 200ms
        # - light.turn_on:
        #     id: rgb
        #     effect: 'Rainbow'
        #     brightness: 20%
        # -  delay: 3s
        # - light.turn_on:
        #     id: rgb
        #     brightness: 20%
        # - light.turn_off: rgb
        - lambda: |-
            id(lcd_display).backlight();
            id(lcd_display).print(0, 0, "Sprinkler Controller");
            id(lcd_display).update();
        - delay: 1s

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_key
  services:
    - service: start_prg_a
      then:
        - script.wait: watering_program_a
        - script.execute: watering_program_a
    - service: start_prg_b
      then:
        - script.wait: watering_program_b
        - script.execute: watering_program_b

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sprinkler Fallback Hotspot"
    password: "HfYeKDfyb5Pc"

captive_portal:

button:
  - platform: restart
    name: "Reboot"
  - platform: template
    name: "Run Watering Program A"
    on_press:
      # - wait_until:
      #     condition: 
      #       switch.is_off: main_switch # Not sure if this is actually needed
      - script.execute: watering_program_a
  - platform: template
    name: "Run Watering Program B"
    on_press:
      # - wait_until:
      #     condition: 
      #       switch.is_off: main_switch # Not sure if this is actually needed
      - script.execute: watering_program_b
  - platform: template
    name: "Stop All Sprinklers"
    on_press:
      - sprinkler.shutdown: sprinkler_controller
      - sprinkler.clear_queued_valves: sprinkler_controller

light:
  # Built in status LED on LilyGo 8x channel relay board
  - platform: binary
    id: status_led
    name: "Status LED"
    output: status_led_gpio
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO15
    default_transition_length: 50ms
    num_leds: 3
    rmt_channel: 0
    chipset: ws2812
    id: rgb
    name: "RGB LED"
  #   effects:
  #     - addressable_rainbow:
  #         name: Rainbow
  #         speed: 10
  #         width: 3

output:
  # Built in status LED on LilyGo 8x channel relay board
  - id: status_led_gpio
    platform: gpio
    pin: GPIO25
    inverted: True

i2c:
  sda: GPIO02
  scl: GPIO14
  frequency: 100kHz

display:
  - platform: lcd_pcf8574
    dimensions: 20x4
    address: 0x27
    id: lcd_display
    lambda: |-
      if (id(sprinkler_controller).active_valve().has_value()) {
        auto running_valve_no = id(sprinkler_controller).active_valve().value();
        auto running_valve_name = id(sprinkler_controller)->valve_name(running_valve_no);

        //                Prog A              
        //                01234567890123456789
        it.printf(0, 0, "%s              ", id(current_program_str).c_str());

        it.printf(0, 1, "%s", running_valve_name);

        //               Valve Time: xx:xx:xx
        //               01234567890123456789
        auto temp = id(sprinkler_controller).time_remaining_active_valve().value();
        it.printf(0, 2, "Valve Time: %s", seconds_to_readable_2(temp));

        //               Total Rem:  xx:xx:xx
        //               01234567890123456789
        temp = id(sprinkler_controller).time_remaining_current_operation().value();
        it.printf(0, 3, "Total Rem:  %s", seconds_to_readable_2(temp));
      }
      else {
        //              01234567890123456789
        it.print(0, 0, "Idle                ");

        it.print(0, 1, "                    ");

        it.print(0, 2, "Valve Time:        0");

        it.print(0, 3, "Total Rem:         0");
      }


###########
#### TODO
###########
# Add physical push buttons, one for each zone

# This component created by https://github.com/kbx81
# https://github.com/kbx81/esphome-configs/blob/main/dev/esp-sprinkler-controller.yaml
sprinkler:
  - id: sprinkler_controller
    main_switch:
      id: main_switch
      name: "Main Switch"
      on_turn_on:
        - light.addressable_set:
            id: rgb
            range_from: 0
            range_to: 2
            color_brightness: 80%
            red: 0.0
            green: 1.0
            blue: 0.0
        - script.execute: publish_sprinkler_time
      on_turn_off:
        - light.addressable_set:
            id: rgb
            range_from: 0
            range_to: 2
            color_brightness: 30%
            red: 1.0
            green: 0.0
            blue: 0.0
        - sprinkler.clear_queued_valves: sprinkler_controller
        - text_sensor.template.publish:
            id: text_time_remaining
            state: "Finished"
        - text_sensor.template.publish:
            id: text_total_queue_time
            state: "0s"
        - text_sensor.template.publish:
            id: text_valve_rem_time
            state: "0s"
        - lambda: 'id(current_program_str) = "No program";'
    auto_advance_switch: "Sprinklers Auto Advance"
    valve_overlap: 5s
    multiplier_number:
      # Defaults are: multiplier: 1.0, min_value: 0.0, max_value: 10, step: 0.1
      name: "Time Multiplier"
      id: multiplier_number
      max_value: 5.0
      mode: box
      # set_action:
      # on_value:
      #   - text_sensor.template.publish:
      #       id: text_time_remaining
      #       state: !lambda |-
      #         return seconds_to_readable(id(sprinkler_controller).time_remaining_current_operation().value());
    valves:
      #
      # Valve 0 - Zone 1 : SHED LAWN
      #
      - valve_switch: ${shed_lawn_name}
        enable_switch: Enable ${shed_lawn_name}
        valve_switch_id: relay1
        run_duration_number:
          name: ${shed_lawn_name} Run Duration
          unit_of_measurement: min
          icon: "mdi:timer-sand"
          initial_value: ${initial_runtime_mins}
          max_value: ${max_runtime_mins}
          mode: box

      #
      # Valve 1 - Zone 2 : RAMP LAWN
      #
      - valve_switch: ${ramp_lawn_name}
        enable_switch: Enable ${ramp_lawn_name}
        valve_switch_id: relay2
        run_duration_number:
          name: ${ramp_lawn_name} Run Duration
          unit_of_measurement: min
          icon: "mdi:timer-sand"
          initial_value: ${initial_runtime_mins}
          max_value: ${max_runtime_mins}
          mode: box

      #
      # Valve 2 -  Zone 3 : BACK LAWN
      #
      - valve_switch: ${back_lawn_name}
        enable_switch: Enable ${back_lawn_name}
        valve_switch_id: relay3
        run_duration_number:
          name: ${back_lawn_name} Run Duration
          unit_of_measurement: min
          icon: "mdi:timer-sand"
          initial_value: ${initial_runtime_mins}
          max_value: ${max_runtime_mins}
          mode: box

      #
      # Valve 3 -  Zone 4 : BACK GARDEN
      #
      - valve_switch: ${back_garden_name}
        enable_switch: Enable ${back_garden_name}
        valve_switch_id: relay4
        run_duration_number:
          name: ${back_garden_name} Run Duration
          unit_of_measurement: min
          icon: "mdi:timer-sand"
          initial_value: ${initial_runtime_mins}
          max_value: ${max_runtime_mins}
          mode: box

      #
      # Valve 4 - Zone 5 : POOL GARDEN
      #
      - valve_switch: ${pool_garden_name}
        enable_switch: Enable ${pool_garden_name}
        valve_switch_id: relay5
        run_duration_number:
          name: ${pool_garden_name} Run Duration
          unit_of_measurement: min
          icon: "mdi:timer-sand"
          initial_value: ${initial_runtime_mins}
          max_value: ${max_runtime_mins}
          mode: box

      #
      # Valve 5 -  Zone 6 : FRONT GARDEN
      #
      - valve_switch: ${front_garden_name}
        enable_switch: Enable ${front_garden_name}
        valve_switch_id: relay6
        run_duration_number:
          name: ${front_garden_name} Run Duration
          unit_of_measurement: min
          icon: "mdi:timer-sand"
          initial_value: ${initial_runtime_mins}
          max_value: ${max_runtime_mins}
          mode: box

      #
      # Valve 6 -  Zone 7 : FRONT LAWN
      #
      - valve_switch: ${front_lawn_name}
        enable_switch: Enable ${front_lawn_name}
        valve_switch_id: relay7
        run_duration_number:
          name: ${front_lawn_name} Run Duration
          unit_of_measurement: min
          icon: "mdi:timer-sand"
          initial_value: ${initial_runtime_mins}
          max_value: ${max_runtime_mins}
          mode: box

      #
      # Valve 7 -  Zone 8 : VERGE LAWN
      #
      - valve_switch: ${verge_lawn_name}
        enable_switch: Enable ${verge_lawn_name}
        valve_switch_id: relay8
        run_duration_number:
          name: ${verge_lawn_name} Run Duration
          unit_of_measurement: min
          icon: "mdi:timer-sand"
          initial_value: ${initial_runtime_mins}
          max_value: ${max_runtime_mins}
          mode: box

switch:
  - platform: gpio
    pin: GPIO33
    id: relay1

  - platform: gpio
    pin: GPIO32
    id: relay2

  - platform: gpio
    pin: GPIO13
    id: relay3

  - platform: gpio
    pin: GPIO12
    id: relay4

  - platform: gpio
    pin: GPIO21
    id: relay5

  - platform: gpio
    pin: GPIO19
    id: relay6

  - platform: gpio
    pin: GPIO18
    id: relay7

  - platform: gpio
    pin: GPIO5
    id: relay8

script:
  #
  # Program A - GARDENS
  #
  - id: watering_program_a
    then:
      - lambda: 'id(current_program_str) = "Prog A";'
      - sprinkler.clear_queued_valves:
          id: sprinkler_controller
      - sprinkler.queue_valve:
          id: sprinkler_controller
          valve_number: 3 # Zone 4 BACK GARDEN
          run_duration: 0s
      - sprinkler.queue_valve:
          id: sprinkler_controller
          valve_number: 4 # Zone 5 POOL GARDEN
          run_duration: 0s
      - sprinkler.queue_valve:
          id: sprinkler_controller
          valve_number: 5 # Zone 6 FRONT GARDEN
          run_duration: 0s
      # Must publish queue time here as once started the first value is removed form queue
      - script.execute: publish_queue_time
      - sprinkler.start_from_queue:
          id: sprinkler_controller
      - script.execute: publish_sprinkler_time

  #
  # Program B - BACK LAWNS
  #
  - id: watering_program_b
    then:
      - lambda: 'id(current_program_str) = "Prog B";'
      - sprinkler.clear_queued_valves:
          id: sprinkler_controller
      - sprinkler.queue_valve:
          id: sprinkler_controller
          valve_number: 0 # Zone 1 SHED LAWN
          run_duration: 0s
      - sprinkler.queue_valve:
          id: sprinkler_controller
          valve_number: 1 # Zone 2 RAMP LAWN
          run_duration: 0s
      - sprinkler.queue_valve:
          id: sprinkler_controller
          valve_number: 2 # Zone 3 BACK LAWN
          run_duration: 0s
      # Must publish queue time here as once started the first value is removed form queue
      - script.execute: publish_queue_time
      - sprinkler.start_from_queue:
          id: sprinkler_controller
      - script.execute: publish_sprinkler_time

  - id: publish_queue_time
    then:
      - text_sensor.template.publish:
          id: text_total_queue_time
          state: !lambda |-
            std::string prog_txt = "";
            prog_txt = id(current_program_str) + " " +
                        seconds_to_readable_1(id(sprinkler_controller).total_queue_time());
            return prog_txt;

  - id: publish_sprinkler_time
    then:
      - while:
          condition:
            lambda: 'return id(sprinkler_controller).time_remaining_current_operation().has_value();'
          then:
            - text_sensor.template.publish:
                id: text_time_remaining
                state: !lambda |-
                  return seconds_to_readable_1(id(sprinkler_controller).time_remaining_current_operation().value());
            - text_sensor.template.publish:
                id: text_valve_rem_time
                state: !lambda |-
                  return seconds_to_readable_1(id(sprinkler_controller).time_remaining_active_valve().value());
            - delay: 5s
      - text_sensor.template.publish:
          id: text_time_remaining
          state: "Finished"

text_sensor:
  - platform: template
    name: Time Remaining
    id: text_time_remaining
    icon: mdi:clock-start
    update_interval: 5min
  - platform: template
    name: Total Program Time
    id: text_total_queue_time
    icon: mdi:clock-start
    update_interval: 5min
  - platform: template
    name: Valve Remaining Time
    id: text_valve_rem_time
    icon: mdi:clock-start
    update_interval: 5min
