esphome:
  name: ttgo-oled-8266
  comment: Lilygo TTGO ESP8266 SSD1306 0.91" 128x32 OLED I2C

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

globals:
  - id: co2_updated
    type: bool
    initial_value: 'false'

font:
  - file: "arial.ttf"
    id: arial_12
    size: 12
  - file: "arial.ttf"
    id: arial_20
    size: 20
    
i2c:
  sda: GPIO2
  scl: GPIO14
  frequency: 700000

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    contrast: 100%
    reset_pin: GPIO4
    address: 0x3C
    id: oled
    lambda: |-
      // id(oled).set_contrast(1.0); // Contrast range: 0.0 - 1.0
      it.printf(20, 7, id(arial_20), "CO2: %.0f", id(co2).state);
      // Blink the update indicator circle
      if (id(co2_updated)) {
        id(co2_updated) = false;
        it.filled_circle(it.get_width() - 7, it.get_height() - 7, 5);
      }

sensor:
  - platform: homeassistant
    internal: true
    id: co2
    entity_id: sensor.scd41_co2_2
    on_value:
      then:
        - globals.set:
            id: co2_updated
            value: 'true'

  - platform: uptime
    name: Uptime Sensor
    internal: true
    id: uptime_sensor
    update_interval: 30s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")).c_str();

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 30s

text_sensor:
  - platform: template
    name: Uptime Human Readable
    id: uptime_human
    icon: mdi:clock-start