substitutions:
  dev_name: "workshop-temperature-ds18b20"
  friend_name: "Workshop Temperature DS18B20"
  ds18b20_internal_addr: "0x513c01a8166a2228"
  ds18b20_external_addr: "0xf200000dfca2d528"

packages:
  device_base: !include packages/device-temperature-ds18b20.yaml

wifi:
  manual_ip:
    static_ip: 192.168.20.248
    gateway: 192.168.20.1
    subnet: 255.255.255.0
